export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_CLUB_PROFILE = 'GET_CLUB_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const GET_MEMBER_UPLOADS = 'GET_MEMBER_UPLOADS';
export const UPLOADS_LOADING = 'UPLOADS_LOADING';
export const ADD_UPLOAD = 'ADD_UPLOAD';
export const DELETE_UPLOAD = 'DELETE_UPLOAD';
export const SET_PHOTO_FILTER_TEXT = 'SET_PHOTO_FILTER_TEXT'
export const SORT_PHOTO_BY_DATE = 'SORT_PHOTO_BY_DATE';
export const SET_PHOTO_FILTER_TITLE = 'SET_PHOTO_FILTER_TITLE';
export const SET_START_DATE = 'SET_START_DATE';
export const SET_END_DATE = 'SET_END_DATE';
export const GET_POSTS = 'GET_POSTS';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const GET_POST = 'GET_POST';


